Esc				EQU 1bh
Cr              EQU 0dh   ; WagenrÅcklauf
Lf              EQU 0ah   ; Linefeed
Ht              EQU 09h   ; horizontel Tab
Vt              EQU 0bh   ; vertical Tab
Ff              EQU 0ch   ; Formfeed
Backspace       EQU 08h
Delete          EQU 7fh
Esc             EQU 1bh
Ctrl_u          EQU 15h
Ctrl_z          EQU 1ah
Strich          EQU 27h

xref Hex2bin
xref Hex4bit
xref Space_test
xref Print_test
xref Upper
xref Char_cmp
xref Is_literal
xref Is_num
xref Is_alpha
