SerialObj_Free	 			.equ PrintfObj_Free
SerialObj_Pointprn 			.equ PrintfObj_Pointprn
SerialObj_MeldOut 			.equ PrintfObj_MeldOut
SerialObj_CharOut 			.equ PrintfObj_CharOut
SerialObj_TermCmd 			.equ PrintfObj_TermCmd
SerialObj_CharIn			.equ 5
SerialObj_TestBaud			.equ 6
SerialObj_SetBaud			.equ 7
SerialObj_GetBaud			.equ 8
SerialObj_Char_get			.equ 9
SerialObj_ClrInBuffer		.equ 10

xref SerialObj